# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuiteLife' do
  pod "Pastel"
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuiteLife
  pod 'Tabman'
  pod 'M13Checkbox'
  pod 'Alamofire'
  pod 'BarcodeScanner'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
end
